version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/springbootapi
permissions:
  - object: /home/ec2-user/springbootapi
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: springbootapi/Scripts/stop_server.sh
      timeout: 3600
      runas: root
  BeforeInstall:
    - location: springbootapi/Scripts/clean_instance.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: springbootapi/Scripts/start_server.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: springbootapi/Scripts/tests.sh
      timeout: 3600
      runas: root
