apiVersion: v1
kind: Service
metadata:
  name: springbootapi-svc-$ENVIRONMENT
  namespace: $NAMESPACE
  labels:
    app.kubernetes.io/name: springbootapi
    app.kubernetes.io/instance: springbootapi
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: springbootapi
    app.kubernetes.io/instance: springbootapi
